[IN-PROGRESS] Integrating sqlite into the project
kareemassad/inventory pull request #3
Opened 2022-08-13 20:59 UTC by kareemassad

Integrating sqlite and importing banknotedb into it.

Currently finish most helper methods and just need to test.

Ran into issues as couldn't resolve table.

2022-08-16 19:43 UTC, aloisclerc requested changes
just a lot of weird repeated code in db.dart and table.dart. widgets and data shouldn't be copy pasted from file to file. also most code should be written in widgets or in functions used by widgets.

2022-08-16 19:43 UTC, aloisclerc commented on lib/table.dart
> +  Map<String, dynamic> toMap() {
what's the difference between this and the toJSON function? is it just the id parameter? could we not just have the id parameter in the toMap function?

2022-08-16 19:43 UTC, aloisclerc commented on lib/db.dart
> +class Banknote {
why is this class in both db.dart and table.dart, just import it from one to the other

2022-08-16 19:43 UTC, aloisclerc commented on lib/db.dart
> +final List<Map<String, String>> inputJSON = [
i get that it's dummy data, but still preferable to not have inputJSON in both db.dart and table.dart just because to simulate real data we gotta imagine it's coming from one place(which soon will be the login page)

2022-08-16 19:43 UTC, aloisclerc commented on lib/db.dart
> +void main() async {
are you sure this should be in a main function? seems like bad flutter practice. not sure where you would put it but maybe in a constructor of an existing widget? for initializing purposes i guess it's fine here but should eventually be moved somewhere else

2022-08-16 19:43 UTC, aloisclerc commented on lib/db.dart
> +  //testing
put tests in a "testing" function so that it's clearly seperated and easy to run(ideally all the tests will be in different files at some point but not worried about that rn)

2022-08-16 19:43 UTC, aloisclerc commented on lib/db.dart
> +class BanknoteTable extends StatefulWidget {
Why is there a copy of BanknoteTable in here, can you not import the function? again just seems like really bad practice

2022-08-16 19:43 UTC, aloisclerc commented on scripts/scrape_table.ipynb
> +{
ima trust you on this file because i've never used this kinda scraping before so it's all u king

2022-08-20 17:16 UTC, aloisclerc approved these changes

2022-08-20 17:17 UTC, aloisclerc requested changes
changes from old commits still seem to be in the pr. remove old commits or the changes made by old commits then it shouldd be good

2022-08-23 21:33 UTC, kareemassad commented on scripts/scrape_table.ipynb
> +{
Try running it you should be able to see it easily in the ipynb

2022-08-23 21:42 UTC, kareemassad reviewed
Finished Cleaning Up. Review and Merge shawty

2022-08-24 04:33 UTC, aloisclerc reviewed
looks good qt

2022-08-24 04:33 UTC, merged